### ISSUE TITLE
Unrecognized function or variable 'JDarrBG'.

### ISSUE THREAD

**Issue by XiangruiJi** [kjamartens/TARDIS-public#1]
Hi,
I tried to run TARDIS_app.mlapp on MATLAB for your example data (Single_Population_1um2s_lowDensity.csv), but got the following error message.

Warning: Column headers from the file were modified to make them valid MATLAB identifiers before creating variable names for the table. The original column headers are saved in
the VariableDescriptions property.
Set 'VariableNamingRule' to 'preserve' to use the original column headers as table variable names. 
No settingsTARDIS.AlternativeLookupPosList provided! Using a pre-set value of 0
Unrecognized function or variable 'JDarrBG'.

Error in URDA_HO_FF_function (line 168)
Visualisation_HO_outputCell.JDarrBG = JDarrBG;

Error in TARDIS_app/RunTARDISButtonPushed (line 1285)
                        URDA_HO_FF_function(poslist,app.Data.settingsURDA);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 172)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error using appdesservices.internal.interfaces.model.AbstractModel/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.

I would appreciate it if you could help me with this issue.

**Comment by kjamartens** [comment]
Hi,
Thank you for reporting your issue.

Unfortunately, I cannot reproduce your error. Could you please let me know the following:
* What operating system are you using?
* What MATLAB version are you using?
* Are you using TARDIS v1.20 or v1.21?
* Did you install the Signal Processing, Curve Fitting, and Optimization toolboxes are stated in the TARDIS manual?

In addition, could you please try to install the latest release of the standalone TARDIS from here: https://github.com/kjamartens/TARDIS-public/releases/tag/release_v121 (TARDISInstaller_v121.exe), assuming you have access to a Windows PC, and let me know if the issue persists?

Alternatively, I made a small change to the URDA_HO_FF_function.m script (commit 49dd462). Could you pull this change, run TARDIS again, and let me know what error message is reported?

Thanks!
Koen

**Comment by XiangruiJi** [comment]
Hi Koen,
Thank you for your reply.

I am using TARDIS v1.21 on MATLAB R2023b, Windows 11, and I've installed these toolboxes (version 23.2).

The standalone TARDIS works.

I pulled this change, and the error message became:
Warning: Column headers from the file were modified to make them valid MATLAB identifiers before creating variable names for the table. The original column headers are saved in
the VariableDescriptions property.
Set 'VariableNamingRule' to 'preserve' to use the original column headers as table variable names. 
No settingsTARDIS.AlternativeLookupPosList provided! Using a pre-set value of 0
There was an error! The message was:
Undefined function 'pdist2' for input arguments of type 'double'.
Unrecognized function or variable 'JDarrBG'.

Error in URDA_HO_FF_function (line 170)
Visualisation_HO_outputCell.JDarrBG = JDarrBG;

Error in TARDIS_app/RunTARDISButtonPushed (line 1285)
                        URDA_HO_FF_function(poslist,app.Data.settingsURDA);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by kjamartens** [comment]
Hi,
Thanks for your quick reply.
Could you please also install the 'Statistics and Machine Learning Toolbox' (https://nl.mathworks.com/products/statistics.html or via MATLAB's Home-->Add-Ons) and see if that fixes your issue?
Appearantly MATLAB has changed whether the pdist2 function is included by default or not.

Cheers,
Koen

**Comment by XiangruiJi** [comment]
Hi Koen,

It works! Thank you very much for your help.

**Comment by kjamartens** [comment]
You're welcome! Happy TARDISing!
