### ISSUE TITLE
Issues about running aDDA

### ISSUE THREAD

**Issue by XiangruiJi** [kjamartens/TARDIS-public#2]
Hi Koen,

I run into a problem when analyzing the example data aDDA_20_20_2_midStructured_midSpurious.csv by aDDA (see the following screenshot).
![image](https://github.com/kjamartens/TARDIS-public/assets/115874380/cdc7b043-8959-4503-95e7-091fe3fffbaf)

I also tried the standalone TARDIS software but it froze (see the following screenshot).
![image](https://github.com/kjamartens/TARDIS-public/assets/115874380/857fd560-a55a-4cbb-8ca4-97036010bba8)

In addition, can I use aDDA to fit systems with two mobile states, apart from systems with an immobile state and a mobile state?

Thanks!

**Comment by kjamartens** [comment]
Hi!

Afraid I can't reproduce the error. I just pushed a change that will provide a more informative error message, can you let me know what it is?

Additionally, can you give me screenshots of the basic/advanced settings tabs?

The anaDDA currently implemented is only for 1 mobile state, 1 immobile state. Please see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7732728/ for the underlying math of anaDDA. If you want to get more info on state-changing between two mobile states, (also) take a look at MC-DDA (not implemented in TARDIS, but you could do TARDIS-JD extraction and run MC-DDA on the resulting JD data), presented here: https://www.nature.com/articles/s41467-019-11514-0 and further updated here: https://www.biorxiv.org/content/10.1101/2023.11.16.567366v1.abstract

Cheers,
Koen

**Comment by XiangruiJi** [comment]
Hi Koen,

The error message is:
![image](https://github.com/kjamartens/TARDIS-public/assets/115874380/ead7fba3-b933-4761-ae3a-74c1f1d2fb49)

Below are my settings. I used default parameters except the start_aDDA, for which I used [20 20 2], as in the csv filename.
![image](https://github.com/kjamartens/TARDIS-public/assets/115874380/6621253b-edf2-4d7b-9121-d10334a58e75)
![image](https://github.com/kjamartens/TARDIS-public/assets/115874380/2d76d468-4aac-4f74-a9fc-6b383afffcf2)
I also tried the parameters stated in your paper, but the result was the same.
![image](https://github.com/kjamartens/TARDIS-public/assets/115874380/10ecb218-5014-470e-ad0c-c0be675d04b6)

Thanks for providing these nice references. I will have a try.

**Comment by kjamartens** [comment]
Hi.

I believe I have fixed the bugs in both the stand-alone and MATLAB-based versions, could you please test?
For the MATLAB version, just pull the changes. For the stand-alone, please install via https://github.com/kjamartens/TARDIS-public/releases/tag/release_v1211

Let me know,
Koen

**Comment by XiangruiJi** [comment]
Hi Koen,
Yes, the bugs have been fixed. Thank you very much.

**Comment by kjamartens** [comment]
You're welcome!
